################
# Language Settings
#
# Sets the default language file
################
lang: en

# How often to check for whitelist updates
update_interval: 1800

# URL to WordPress installation
url: "http://playground.jays.link"

# Server security key
key: ""

##########################
#   Ignore usernames
# Typically you WANT your
# username here if you're
# the admin.
##########################
ignoreRemove:
  - phyrax